{% set name = "keras2onnx" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/keras-onnx/archive/v{{ version }}.tar.gz
  sha256: 22f01ed87e251efc00835bb8120fa236d84c61361d2ffc0412f3b04f8894841b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - protobuf
    - requests
    - onnx
    - onnxconverter-common >=1.6,<1.7
    - fire
    - tensorflow

test:
  imports:
    - keras2onnx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/keras-onnx
  summary: Convert tf.keras/Keras models to ONNX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
