{% set name = "keras2onnx" %}
{% set version = "1.6.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/onnx/keras-onnx/archive/v{{ version }}.tar.gz
  sha256: a8cab4b7733b306f539d0bbf637fbb43aec67b6fd2c74887afe189749ce1b673

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - protobuf
    - requests
    - onnx
    - onnxconverter-common >=1.6.5
    - fire
    - tensorflow

test:
  imports:
    - keras2onnx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/onnx/keras-onnx
  summary: Convert tf.keras/Keras models to ONNX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
